// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-77JMTA56D2x-i5rebO1tLoRo0v1IaI',
    appId: '1:838679366640:web:5016fe8c0283f85830ab35',
    messagingSenderId: '838679366640',
    projectId: 'medicationtracker-8ce68',
    authDomain: 'medicationtracker-8ce68.firebaseapp.com',
    storageBucket: 'medicationtracker-8ce68.appspot.com',
    measurementId: 'G-SL2QGZND36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO7nuR5fI5ydWKe3kfMHA401XNPbGl7nM',
    appId: '1:838679366640:android:ff81899a1cdf702330ab35',
    messagingSenderId: '838679366640',
    projectId: 'medicationtracker-8ce68',
    storageBucket: 'medicationtracker-8ce68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCY4sMpnLhEnsluJVn34GsKY0-hDh6RDs',
    appId: '1:838679366640:ios:9ec09db18fc4c84c30ab35',
    messagingSenderId: '838679366640',
    projectId: 'medicationtracker-8ce68',
    storageBucket: 'medicationtracker-8ce68.appspot.com',
    iosBundleId: 'com.example.medicationReminderVscode',
  );
}
